version: "3"

services:
  imperva-web-api-composer:
    # image: registry.gitlab.com/imperva-community/public/tools/imperva-web-api-composer:latest
    build: .
    # volumes:
    #  - ./target/:/usr/local/tomcat/webapps/
    ports:
    - 8080:8080
    - 8443:443
    environment:
      TZ: ${TZ:-UTC}
      CONTAINER_NAME: imperva-web-api-composer

